# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma_mc <- function(x, mean, sigma, logd = FALSE, cores = 1L) {
    .Call('MScPack_dmvnrm_arma_mc', PACKAGE = 'MScPack', x, mean, sigma, logd, cores)
}

.drmFFBSdiscW <- function(Y, X, dV, discW, m0, ZC0) {
    .Call('MScPack_drmFFBSdiscW', PACKAGE = 'MScPack', Y, X, dV, discW, m0, ZC0)
}

.FactorSim <- function(Y, Lambda, psi) {
    .Call('MScPack_FactorSim', PACKAGE = 'MScPack', Y, Lambda, psi)
}

#' Algoritmo de Gibbs para F-DLM
#' 
#' Estima as quantidades do modelo dinamico fatorial de acordo com os resultados presentes na dissertacao.
#' @param N tamanho final da amostra.
#' @param brn periodo de aquecimento do algoritmo.
#' @param model modelo F-DLM com valores da matriz de dados, de exogenas e hiperparametros da priori.
#' @param initVal valores iniciais para Beta, Lambda e psi.
#' @return Lista com modelo e valores simulados do Gibbs.
fdlmGibbs <- function(N, brn, thn, model, initVal, progressBar = TRUE, onlyValues = FALSE) {
    .Call('MScPack_fdlmGibbs', PACKAGE = 'MScPack', N, brn, thn, model, initVal, progressBar, onlyValues)
}

#' Algoritmo de Gibbs para F-DLM (Choleski)
#' 
#' Estima as quantidades do modelo dinamico fatorial de acordo com os resultados presentes na dissertacao.
#' @param N tamanho final da amostra.
#' @param brn periodo de aquecimento do algoritmo.
#' @param thn espacamento entre as extracoes.
#' @param model modelo F-DLM com valores da matriz de dados, de exogenas e hiperparametros da priori.
#' @param initVal valores iniciais para Beta, Lambda e psi.
#' @return Lista com modelo e valores simulados do Gibbs.
fdlmGibbs_chol <- function(N, brn, thn, model, initVal, progressBar = TRUE, onlyValues = FALSE) {
    .Call('MScPack_fdlmGibbs_chol', PACKAGE = 'MScPack', N, brn, thn, model, initVal, progressBar, onlyValues)
}

#' Algoritmo de Gibbs para F-DLM com NA
#' 
#' Estima as quantidades do modelo dinamico fatorial de acordo com os resultados presentes na dissertacao.
#' @param N tamanho final da amostra.
#' @param brn periodo de aquecimento do algoritmo.
#' @param thn espacamento entre as extracoes.
#' @param model modelo F-DLM com valores da matriz de dados, de exogenas e hiperparametros da priori.
#' @param initVal valores iniciais para Beta, Lambda e psi.
#' @return Lista com modelo e valores simulados do Gibbs.
fdlmGibbsNA <- function(N, brn, thn, model, initVal, progressBar = TRUE, onlyValues = FALSE) {
    .Call('MScPack_fdlmGibbsNA', PACKAGE = 'MScPack', N, brn, thn, model, initVal, progressBar, onlyValues)
}

#' Algoritmo de Gibbs para F-DLM
#' 
#' Estima as quantidades do modelo dinamico fatorial de acordo com os resultados presentes na dissertacao.
#' @param N tamanho final da amostra.
#' @param brn periodo de aquecimento do algoritmo.
#' @param model modelo F-DLM com valores da matriz de dados, de exogenas e hiperparametros da priori.
#' @param initVal valores iniciais para Beta, Lambda e psi.
#' @return Lista com modelo e valores simulados do Gibbs.
fdlmGibbsOnly1 <- function(N, brn, thn, model, initVal, progressBar = TRUE, onlyValues = FALSE) {
    .Call('MScPack_fdlmGibbsOnly1', PACKAGE = 'MScPack', N, brn, thn, model, initVal, progressBar, onlyValues)
}

#' Quantidades iniciais para Gibbs F-DLM
#' 
#' Calculo de quantidades inicias para evitar repeticao de operacoes identicas a cada iteracao do algoritmo de Gibbs..
#' @param model modelo F-DLM com valores da matriz de dados, de exogenas e hiperparametros da priori.
#' @return Lista com modelo e valores iniciais para a cadeia do Gibbs.
fdlmInitQuant <- function(model, modelOut = TRUE) {
    .Call('MScPack_fdlmInitQuant', PACKAGE = 'MScPack', model, modelOut)
}

fdlmLogLik <- function(Y, xFix, xDyn, nFactors, hyperparms, Y_NA, whichNA, Beta, Lambda, psi, discW) {
    .Call('MScPack_fdlmLogLik', PACKAGE = 'MScPack', Y, xFix, xDyn, nFactors, hyperparms, Y_NA, whichNA, Beta, Lambda, psi, discW)
}

fdlmLogLik_chol <- function(Y, xFix, xDyn, nFactors, hyperparms, Y_NA, whichNA, Beta, Lambda, psi, discW) {
    .Call('MScPack_fdlmLogLik_chol', PACKAGE = 'MScPack', Y, xFix, xDyn, nFactors, hyperparms, Y_NA, whichNA, Beta, Lambda, psi, discW)
}

fdlmLogLik_chol_mc <- function(Y, xFix, xDyn, nFactors, hyperparms, Y_NA, whichNA, Beta, Lambda, psi, discW, cores) {
    .Call('MScPack_fdlmLogLik_chol_mc', PACKAGE = 'MScPack', Y, xFix, xDyn, nFactors, hyperparms, Y_NA, whichNA, Beta, Lambda, psi, discW, cores)
}

fdlmLogLik_mc <- function(Y, xFix, xDyn, nFactors, hyperparms, Y_NA, whichNA, Beta, Lambda, psi, discW, cores) {
    .Call('MScPack_fdlmLogLik_mc', PACKAGE = 'MScPack', Y, xFix, xDyn, nFactors, hyperparms, Y_NA, whichNA, Beta, Lambda, psi, discW, cores)
}

.LambdaSimMV <- function(Y, Factors, psi, L0H0Inv, H0Inv) {
    .Call('MScPack_LambdaSimMV', PACKAGE = 'MScPack', Y, Factors, psi, L0H0Inv, H0Inv)
}

isNA <- function(x) {
    .Call('MScPack_isNA', PACKAGE = 'MScPack', x)
}

cleanNA <- function(x) {
    .Call('MScPack_cleanNA', PACKAGE = 'MScPack', x)
}

whichNA <- function(X) {
    .Call('MScPack_whichNA', PACKAGE = 'MScPack', X)
}

changeNA <- function(X) {
    .Call('MScPack_changeNA', PACKAGE = 'MScPack', X)
}

.parmsFixRegSim <- function(Y, X, B1, ZB1, psi, B0Invb0) {
    .Call('MScPack_parmsFixRegSim', PACKAGE = 'MScPack', Y, X, B1, ZB1, psi, B0Invb0)
}

.psiSim <- function(Y, Beta, b0, B0Inv, Lambda, L0, H0Inv, n0, s0) {
    .Call('MScPack_psiSim', PACKAGE = 'MScPack', Y, Beta, b0, B0Inv, Lambda, L0, H0Inv, n0, s0)
}

