# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Algoritmo de Gibbs para F-DLM
#' 
#' Estima as quantidades do modelo dinamico fatorial de acordo com os resultados presentes na dissertacao.
#' @param N tamanho final da amostra.
#' @param brn periodo de aquecimento do algoritmo.
#' @param model modelo F-DLM com valores da matriz de dados, de exogenas e hiperparametros da priori.
#' @param initVal valores iniciais para Beta, Lambda e psi.
#' @return Lista com modelo e valores simulados do Gibbs.
fdlmGibbs <- function(N, brn, thn, model, initVal) {
    .Call('MScPack_fdlmGibbs', PACKAGE = 'MScPack', N, brn, thn, model, initVal)
}

